### ISSUE TITLE
Añadirme a los pushers si queréis mis cosas

### ISSUE THREAD

**Issue by Morgloz** [asrob-uc3m/ASROB-CADE#1]
Pues eso, que si queréis mis conocimientos tendréis que dejarme hacer push.

**Comment by jgvictores** [comment]
Puedes hacer un PR?  😀

**Comment by jgvictores** [comment]
Te metí en [asrob-uc3m/teams/g-a-m-e](https://github.com/orgs/asrob-uc3m/teams/g-a-m-e) (hace falta estar logueado para acceder al link).

**Comment by David-Estevez** [comment]
He añadido además a los que estuvísteis hoy currando en la máquina. Si alguno más quiere participar en G.A.M.E  que lo diga el próximo día y se le mete.
