### ISSUE TITLE
Arreglar la recreativa para la Feria de Asociaciones

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/ASROB-CADE#8]
Cosas que le pasan actualmente a la recreativa:

  * [x] No hay tarjeta SD (Está perdida).
  * [x] El Arduino está mal  programado.

Bonus:

 *  [x] No funciona el contador de monedas.

~¿Voluntarios para solucionar esta issue?~ Edit: @jorgercobo se ofreció voluntario via Telegram.

**Comment by jorgercobo** [comment]
La máquina ya es funcional

**Comment by jorgercobo** [comment]
Como la maquina ya se podría usar en la feria y solo queda el bonus, abro issue aparte #10
